backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  # This line should *not* be indented
publish_mode: editorial_workflow

media_folder: "/static" # Folder where user uploaded files should go
public_folder: "/static"

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "/content/posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
       - {label: "category", name: "category", widget: "string"}
       - {label: "cover", name: "cover", widget: "image", required: false}
       - {label: "Автор", name: "author", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
 
