backend:
  name: github
  repo: brovnjons/gatsby-starter-hero-blog # Path to your Github repository
  branch: master # Branch to update



media_folder: "static/img/" # Media files will be stored in the repo under static/images/uploads
public_folder: "static/img/" # The src attribute for uploaded media will begin with /images/uploads

    


    collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Posts" # Used in the UI
    label_singular: "Post" # Used in the UI, ie: "New Post"
    folder: "content/posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "category", name: "category", widget: "string"}
      - {label: "Cover Image", name: "cover", widget: "image", required: false, tagname: ""}
      - {label: "author", name: "author", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
